#!/bin/bash
# The logic to start up your application should be put in this
# script. The application will work only if it binds to
# $OPENSHIFT_INTERNAL_IP:8080
# nohup $OPENSHIFT_REPO_DIR/diy/testrubyserver.rb $OPENSHIFT_INTERNAL_IP $OPENSHIFT_REPO_DIR/diy > $OPENSHIFT_DIY_LOG_DIR/server.log 2>&1 &
# replace the $OPENSHIFT_INTERNAL_IP and $OPENSHIFT_INTERNAL_PORT before starting up the server
sed -e "s/\$OPENSHIFT_IP:\$OPENSHIFT_PORT'/$OPENSHIFT_PYTHON_IP:$OPENSHIFT_PYTHON_PORT/" \
-e "s/\$OPENSHIFT_DATA/$OPENSHIFT_DATA_DIR/" \
$OPENSHIFT_DATA_DIR/conf/nginx.conf.template > $OPENSHIFT_DATA_DIR/conf/nginx.conf
nohup $OPENSHIFT_DATA_DIR/sbin/nginx > $OPENSHIFT_PYTHON_LOG_DIR/server.log 2>&1 &
